name: example-environment
channels:
  - psi4/label/dev
  - conda-forge
  - omnia
dependencies:
  - python
  - numpy
  - scipy
  - rdkit
  - psi4
  - dftd3
  - ipywidgets
  - widgetsnbextension
  - scikit-image
  - openmm
  - mdtraj
  - pcmsolver
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - altair
    - matplotlib
    - pythreejs
    - fortecubeview
    - nglview
    
